"""Add new columns and indexes to student_assessment_data

Revision ID: bcfef39d5cf7
Revises: 
Create Date: 2025-06-12 20:37:11.732436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcfef39d5cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Only update student_assessment_data: alter columns if needed
    with op.batch_alter_table('student_assessment_data', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.alter_column('present_absent',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
        # Indexes already exist, so do not create them again
        # batch_op.create_index('idx_sad_competency_level', ['competency_level_name'], unique=False)
        # batch_op.create_index('idx_sad_dashboard_filters', ['assessment_type', 'academic_year', 'subject_name', 'school_name', 'grade_name', 'division_name'], unique=False)
        # batch_op.create_index('idx_sad_student_id', ['student_id'], unique=False)
        # batch_op.create_index('idx_sad_student_name', ['student_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_school', ['school'], unique=False)
        batch_op.create_index('idx_user_roles_role', ['role'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('swptm_attendance_data', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('grade_name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('student_attendance_data', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('student_assessment_data', schema=None) as batch_op:
        batch_op.drop_index('idx_sad_student_name')
        batch_op.drop_index('idx_sad_student_id')
        batch_op.drop_index('idx_sad_dashboard_filters')
        batch_op.drop_index('idx_sad_competency_level')
        batch_op.create_index('idx_subject', ['subject_name'], unique=False)
        batch_op.create_index('idx_student', ['student_id'], unique=False)
        batch_op.create_index('idx_school_year_type', ['school_name', 'academic_year', 'assessment_type'], unique=False)
        batch_op.create_index('idx_assessment_date', ['assessment_date'], unique=False)
        batch_op.alter_column('present_absent',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)

    with op.batch_alter_table('ptm_attendance_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Active'"), nullable=True))
        batch_op.create_index('UQ_ptm_attendance_data_unique_key', ['ptm_attendance_data_unique_key'], unique=True)
        batch_op.alter_column('ptm_attendance_data_unique_key',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('division_name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('attendance_percentage',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=1),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('grade_name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('present_ptm',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('non_standardised_assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_standard_assessment_unique_key', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('last_updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Active'"), nullable=False))
        batch_op.create_index('non_standard_assessment_unique_key', ['non_standard_assessment_unique_key'], unique=True)
        batch_op.alter_column('assessment_type',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('academic_year',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('max_marks',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('present_absent',
               existing_type=sa.String(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('question_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('student_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('assessment_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('division_name',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('course_name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('assessment_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('grade_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('percentage',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('school_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('obtained_marks',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('assessment_id2')

    with op.batch_alter_table('active_student_data', schema=None) as batch_op:
        batch_op.create_index('idx_active_student_data_student_id', ['student_id'], unique=False)
        batch_op.create_index('idx_active_student_data_status', ['status'], unique=False)
        batch_op.create_index('idx_active_student_data_school_name', ['school_name'], unique=False)
        batch_op.create_index('idx_active_student_data_grade_name', ['grade_name'], unique=False)
        batch_op.create_index('idx_active_student_data_gender', ['gender'], unique=False)
        batch_op.create_index('idx_active_student_data_division_name', ['division_name'], unique=False)
        batch_op.create_index('idx_active_student_data_composite_school', ['school_name', 'academic_year', 'grade_name'], unique=False)
        batch_op.create_index('idx_active_student_data_composite_demographics', ['gender', 'academic_year'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('gender',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)

    op.create_table('epv',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('employee_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('from_date', sa.DATE(), nullable=False),
    sa.Column('to_date', sa.DATE(), nullable=False),
    sa.Column('payment_to', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('acknowledgement', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('document_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('requested_documents', mysql.TEXT(), nullable=True),
    sa.Column('submission_date', mysql.DATETIME(), nullable=True),
    sa.Column('academic_year', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cost_center_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cost_center_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('drive_file_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=False),
    sa.Column('amount_in_words', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('invoice_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('master_invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('split_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('approved_amount', mysql.FLOAT(), nullable=True),
    sa.Column('rejected_amount', mysql.FLOAT(), nullable=True),
    sa.Column('pending_amount', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('finance_status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('being_processed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('processing_started_at', mysql.DATETIME(), nullable=True),
    sa.Column('approver_emails', mysql.TEXT(), nullable=True),
    sa.Column('approved_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('approved_on', mysql.DATETIME(), nullable=True),
    sa.Column('rejected_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('rejected_on', mysql.DATETIME(), nullable=True),
    sa.Column('rejection_reason', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('`from_date` <= `to_date`', name='check_date_range'),
    sa.CheckConstraint('`total_amount` >= 0', name='check_positive_amount'),
    sa.ForeignKeyConstraint(['being_processed_by'], ['employee_details.id'], name='epv_ibfk_3'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['costcenter.id'], name='epv_ibfk_1'),
    sa.ForeignKeyConstraint(['master_invoice_id'], ['epv.id'], name='epv_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('epv', schema=None) as batch_op:
        batch_op.create_index('ix_epv_to_date', ['to_date'], unique=False)
        batch_op.create_index('ix_epv_status', ['status'], unique=False)
        batch_op.create_index('ix_epv_from_date', ['from_date'], unique=False)
        batch_op.create_index('ix_epv_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_epv_email_id', ['email_id'], unique=False)
        batch_op.create_index('epv_id', ['epv_id'], unique=True)

    op.create_table('expense_head',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('head_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('head_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('epv_approval',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('allocation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('approver_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('approver_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('action_date', mysql.DATETIME(), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['epv_allocation.id'], name='epv_approval_ibfk_2'),
    sa.ForeignKeyConstraint(['epv_id'], ['epv.id'], name='epv_approval_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('epv_approval', schema=None) as batch_op:
        batch_op.create_index('token', ['token'], unique=True)
        batch_op.create_index('ix_epv_approval_status', ['status'], unique=False)
        batch_op.create_index('ix_epv_approval_approver_email', ['approver_email'], unique=False)

    op.create_table('epv_allocation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cost_center_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cost_center_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('allocated_amount', mysql.FLOAT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('expense_head', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('approver_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('approver_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('action_date', mysql.DATETIME(), nullable=True),
    sa.Column('rejection_reason', mysql.TEXT(), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['costcenter.id'], name='epv_allocation_ibfk_2'),
    sa.ForeignKeyConstraint(['epv_id'], ['epv.id'], name='epv_allocation_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('epv_allocation', schema=None) as batch_op:
        batch_op.create_index('token', ['token'], unique=True)

    op.create_table('epv_item',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('expense_invoice_date', sa.DATE(), nullable=False),
    sa.Column('expense_head', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('gst', mysql.FLOAT(), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('receipt_filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('receipt_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('receipt_drive_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('split_invoice', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epv_id'], ['epv.id'], name='epv_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('costcenter',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('costcenter', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('approver_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('drive_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('costcenter', schema=None) as batch_op:
        batch_op.create_index('ix_costcenter_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_costcenter_costcenter', ['costcenter'], unique=False)
        batch_op.create_index('ix_costcenter_city', ['city'], unique=False)
        batch_op.create_index('ix_costcenter_approver_email', ['approver_email'], unique=False)

    op.create_table('finance_entry',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('finance_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('entry_date', mysql.DATETIME(), nullable=True),
    sa.Column('vendor_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('journal_entry', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('payment_voucher', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('fcra_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('is_partial_payment', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('journal_entry_1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_voucher_1', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amount_1', mysql.FLOAT(), nullable=True),
    sa.Column('fcra_status_1', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_id_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment_date_1', mysql.DATETIME(), nullable=True),
    sa.Column('journal_entry_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_voucher_2', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amount_2', mysql.FLOAT(), nullable=True),
    sa.Column('fcra_status_2', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('transaction_id_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment_date_2', mysql.DATETIME(), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('approver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('approved_on', mysql.DATETIME(), nullable=True),
    sa.Column('rejection_reason', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['employee_details.id'], name='finance_entry_ibfk_3'),
    sa.ForeignKeyConstraint(['epv_id'], ['epv.id'], name='finance_entry_ibfk_1'),
    sa.ForeignKeyConstraint(['finance_user_id'], ['employee_details.id'], name='finance_entry_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('supplementary_document',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('epv_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('drive_file_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('uploaded_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('uploaded_on', mysql.DATETIME(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['epv_id'], ['epv.id'], name='supplementary_document_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('city_assignment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('assigned_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('assigned_on', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employee_details.id'], name='city_assignment_ibfk_2'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_details.id'], name='city_assignment_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('drop_out_students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('city_head_approval_status', mysql.CHAR(length=10), nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sl_approval_status', mysql.CHAR(length=10), nullable=False),
    sa.Column('status', mysql.CHAR(length=50), nullable=False),
    sa.Column('grade_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('student_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gender', mysql.CHAR(length=1), nullable=False),
    sa.Column('division_name', mysql.CHAR(length=50), nullable=False),
    sa.Column('drop_out_from_year', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('drop_out_category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('drop_out_from_month', mysql.CHAR(length=50), nullable=True),
    sa.Column('drop_out_reason_type', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('drop_out_description', mysql.VARCHAR(length=5000), nullable=True),
    sa.Column('final_drop_out_date', sa.DATE(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('drop_out_students', schema=None) as batch_op:
        batch_op.create_index('student_id', ['student_id'], unique=True)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('student_data_history',
    sa.Column('history_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('unique_key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('change_type', mysql.ENUM('INSERT', 'UPDATE', 'INACTIVATE'), nullable=False),
    sa.Column('field_changed', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('old_value', mysql.TEXT(), nullable=True),
    sa.Column('new_value', mysql.TEXT(), nullable=True),
    sa.Column('change_timestamp', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('history_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bucket', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('average', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('employee_details',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('employee_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('manager', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('manager_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employee_details', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('settings_finance',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('setting_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.Column('previous_value', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('settings_finance', schema=None) as batch_op:
        batch_op.create_index('setting_name', ['setting_name'], unique=True)

    op.drop_table('all_assessments')
    # ### end Alembic commands ###
